Update patch set 1
Patch Set 1: Code-Review-1 Verified-1

(1 comment)

The plugin still uses version 0.1-5 of gitiles, so this breaks the build in standalone mode.

 error: com.googlesource.gerrit.plugins.gitiles.GerritGitilesAccess is not abstract and
 does not override abstract method listRepositories(java.util.Set<java.lang.String>)
 in com.google.gitiles.GitilesAccess class GerritGitilesAccess implements GitilesAccess {

We should make a new gitiles release and then make this fix at the same time as updating the version.

Patch-set: 1
Label: Code-Review=-1
Label: Verified=-1