Update patch set 3
Patch Set 3: -Verified

The standalone build fails. It can't find the FileHistoryWeblink.
I built the api and installed it, the plugin api for 2.12-SNAPSHOT seems to lie there good and ready but to no avail...
What am I missing?

[1]
 .../gerrit-plugins/gitiles/src/main/java/com/googlesource/gerrit/plugins/gitiles/GitilesWeblinks.java:20: error: cannot find symbol
import com.google.gerrit.extensions.webui.FileHistoryWebLink;

Patch-set: 3