fix: cannot build 'gerrit-3.2' on MacOS
When `bazel build release` is called the following issue is being
thrown:
  ERROR: /Users/jacek.centkowski/workspace/open/open-source/gerrit/plugins/gitiles/BUILD:23:9: Executing genrule //plugins/gitiles:gitiles-servlet-resources failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

  Use --sandbox_debug to see verbose messages from the sandbox
  sed: -I or -i may not be used with stdin
  Target //plugins/gitiles:gitiles failed to build

It seems that 'Load fonts directly from Gerrit instead of 3rd party
domains' introduced the `sed` transformation that is not supported under
MacOS. As suggested in [1] the most portable way is to handle the backup
file in the command line (at least it works on MacOS ;)).

[1] https://stackoverflow.com/a/21243111

Bug: Issue 15307
Change-Id: I3c40bc42d0a0d1a25aacd1cd2687af03970f88b4